services:
  - type: web
    name: cdi-achados-criticos-dashboard
    runtime: docker
    dockerContext: ./achados_criticos
    dockerfilePath: ./achados_criticos/Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "false"
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
